# Generated by Django 6.0.7 on 2026-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Цена (₸)')),
                ('category', models.CharField(choices=[('simple', 'Обычная услуга (Чекбокс)'), ('length', 'Услуга с выбором длины (Выпадающий список)')], default='simple', max_length=50, verbose_name='Тип услуги')),
            ],
        ),
    ]
