# Generated by Django 6.0.7 on 2026-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.IntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото ногтей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
